# Generated by Django 2.2.4 on 2019-11-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Site Name')),
                ('url', models.URLField(help_text="Website's root url without scheme (http/https)", verbose_name='Site URL')),
                ('is_verified', models.BooleanField(default=False)),
                ('unique_id', models.UUIDField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(blank=True, max_length=64, null=True, verbose_name='IP Address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='First Visited')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Visited')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Client')),
            ],
        ),
    ]
