# Generated by Django 2.2.4 on 2019-11-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Site Visit Count', 'verbose_name_plural': 'Site Visit Counts'},
        ),
    ]
