# Generated by Django 2.2.4 on 2019-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20191123_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='unique_id',
            field=models.CharField(max_length=50),
        ),
    ]
