# Generated by Django 2.2.4 on 2019-11-23 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0004_auto_20191123_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('user', 'url')},
        ),
    ]
