# Generated by Django 2.2.4 on 2019-11-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20191123_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Page Visit Count', 'verbose_name_plural': 'Page Visit Counts'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='track_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Track ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(help_text='URL must be with or without scheme (http/https)', verbose_name='Site URL'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='URL must be with or without scheme (http/https)')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Client')),
            ],
            options={
                'unique_together': {('host', 'url')},
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Page'),
        ),
    ]
