# Generated by Django 2.2.4 on 2019-11-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20191130_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='page',
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('visit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.Visit')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Page')),
            ],
            options={
                'verbose_name': 'Website Visit Count',
                'verbose_name_plural': 'Website Visit Counts',
            },
            bases=('analytics.visit',),
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('visit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.Visit')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Page')),
            ],
            options={
                'verbose_name': 'Page Visit Count',
                'verbose_name_plural': 'Page Visit Counts',
            },
            bases=('analytics.visit',),
        ),
    ]
