# Generated by Django 2.2.4 on 2019-11-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20191130_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='page',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Client'),
        ),
    ]
