# Generated by Django 2.2.4 on 2019-11-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20191130_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='updated',
        ),
    ]
