# Generated by Django 2.2.4 on 2019-12-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_remove_visit_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keyword',
            field=models.CharField(help_text='Must be unique in same domain', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('host', 'keyword')},
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
    ]
