# Generated by Django 2.2.4 on 2019-12-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20191201_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Visited'),
        ),
    ]
