# Generated by Django 2.2.4 on 2019-12-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbAdAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_id', models.CharField(max_length=50, verbose_name='Ads ID')),
                ('account_id', models.CharField(max_length=30, verbose_name='Account ID')),
                ('fb_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth', verbose_name='Social Auth Model')),
            ],
            options={
                'verbose_name': 'Ad Account',
                'verbose_name_plural': 'Ad Accounts',
            },
        ),
    ]
