# Generated by Django 2.2.4 on 2019-12-21 21:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0002_fbadaccount_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_api.FbAdAccount', verbose_name='Ad Account')),
            ],
        ),
    ]
