# Generated by Django 2.2.4 on 2020-01-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_api', '0003_insightdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insightdata',
            options={'get_latest_by': ['created_at']},
        ),
        migrations.AddField(
            model_name='insightdata',
            name='days_count',
            field=models.IntegerField(default=30),
        ),
    ]
