# Generated by Django 2.2.4 on 2019-12-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_user', '0004_auto_20191109_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
